### ISSUE TITLE
cannot import name 'exceptions' from 'asyncio'

### ISSUE THREAD

**Issue by EnricoBeltramo** [cirospaciari/socketify.py#123]
**Describe the bug**

**To Reproduce**
installed with pip

do a simple import:
from socketify import App, AppOptions, OpCode, CompressOptions

and I have this error:
cannot import name 'exceptions' from 'asyncio'

I temporay removed the import from init, and the library work correctly (5x time more fast than with websockets library)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser na
 - Version 0.0.20

**Additional context**

**Comment by eirnym** [comment]
Which exact version of Python do you use?

I've tested on Python 3.10 and 3.11. Both of versions showed, that `from asyncio import exceptions` runs correctly

**Comment by EnricoBeltramo** [comment]
Due some issue compatibility with other pip in my application, I'm using python 3.7

**Comment by cirospaciari** [comment]
> Due some issue compatibility with other pip in my application, I'm using python 3.7

Try a more recent version of python, support for 3.7 will be dropped

**Comment by cirospaciari** [comment]
Yesterday was the last day we supported python 3.7 because its become End Of Life https://github.com/cirospaciari/socketify.py/releases/tag/v0.0.22

We will try to follow the official roadmap for support, but probably focus on 3.9/3.10+ compatibility since PyPy is  Python 3.10 compatible since [2023-06-16 04:22](https://www.pypy.org/posts/2023/06/pypy-v7312-release.html)

https://devguide.python.org/versions/

![image](https://github.com/cirospaciari/socketify.py/assets/6379399/ae271dd9-c39e-4d5d-a52a-5fc1260277a7)
