### ISSUE TITLE
Bind port 80 Issue

### ISSUE THREAD

**Issue by binhvq** [cirospaciari/socketify.py#209]
python -m socketify web:run -w 1 --host 0.0.0.0 --port 80

 `Exception ignored from cffi callback <function uws_generic_listen_handler at 0x7f686d197f70>:
Traceback (most recent call last):
  File "/home/binh/work/backend/shadowbots-api/.venv/lib/python3.9/site-packages/socketify/socketify.py", line 1034, in uws_generic_listen_handler
    raise RuntimeError("Failed to listen on port %d" % int(config.port))
RuntimeError: Failed to listen on port 80
`

Checking:
> lsof -i:80

Output empty.

Why can't not bind to port 80,

**Comment by ArthoPacini** [comment]
Probably because you already got some process listening on port 80, if you are in a unix system you can check this by running `lsof -i :80`, it will display any processes already attached to port 80. 

If there is no process listening on 80, then your OS probably doesn't allow your process to listen to low ports (< 1024), if not running using a privileged user.

Try running with any other available port, it will probably be able to listen to it.

**Comment by binhvq** [comment]
Thanks!
I was try on new vps, It's worked.
Bind 80 port success.
